### ISSUE TITLE
Firefox 81.0.1: "TypeError: window.visualViewport is undefined"

### ISSUE THREAD

**Issue by ghost** [pouyio/twiso#28]
The following error is thrown if you open the app in Firefox:

`TypeError: window.visualViewport is undefined`

Safari e.g. works without problem!

**Comment by pouyio** [comment]
Thanks for the warning!

Just deployed [the fix](https://github.com/pouyio/twiso/blob/master/CHANGELOG.md#2627-2020-10-13)
